name: Test R with renv

on:
  push:
    branches:
      - main  # Se ejecuta cuando subes cambios a la rama principal
  pull_request:
    branches:
      - main  # Se ejecuta cuando alguien hace un Pull Request

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4  

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2' 

      - name: Configurar renv y restaurar paquetes
        uses: r-lib/actions/setup-renv@v2  # Instala renv y ejecuta renv::restore()

      - name: Ejecutar script de prueba
        run: Rscript Script.R  
